# Generated by Django 5.1.7 on 2025-04-02 15:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pastor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('matric_no', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], default='MALE', max_length=20)),
                ('level', models.CharField(choices=[('300', '300L'), ('400', '400L'), ('100', '100L'), ('500', '500L'), ('200', '200L')], default='100', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('course', models.CharField(choices=[('ARTS', 'Arts and Humanities'), ('SCIENCE', 'Science and Technology'), ('SOCIAL_SCIENCE', 'Social Science'), ('ENGINEERING', 'Engineering'), ('LAW', 'Law'), ('MEDICAL_SCIENCES', 'Medical Sciences')], default='ARTS', max_length=50)),
                ('fingerprint', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
