# Generated by Django 5.1.6 on 2025-04-13 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='day',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='period',
        ),
        migrations.AddField(
            model_name='student',
            name='chapel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.chapel'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fingerprint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=20)),
                ('period', models.CharField(choices=[('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], max_length=20)),
                ('chapel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.chapel')),
            ],
            options={
                'unique_together': {('day', 'period', 'chapel')},
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.session'),
        ),
    ]
