# Generated by Django 5.1.6 on 2025-04-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_fingerprint_student_left_fingerprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('400', '400L'), ('500', '500L'), ('300', '300L'), ('100', '100L'), ('200', '200L')], default='100', max_length=20),
        ),
    ]
