# Generated by Django 5.1.6 on 2025-04-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_session_unique_together_session_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('500', '500L'), ('200', '200L'), ('400', '400L'), ('100', '100L'), ('300', '300L')], default='100', max_length=20),
        ),
    ]
