# Generated by Django 5.1.6 on 2025-04-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('300', '300L'), ('200', '200L'), ('400', '400L'), ('500', '500L'), ('100', '100L')], default='100', max_length=20),
        ),
    ]
